name: null
favicon: null
layout_spectrum: 0.6678186608478427
typography_spectrum: 0.8405235609970987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.47226668149232864
  lightness: 0.7461369545198977
  saturation: 0.21191151603125036
  rhythmicContrast: 0.6772748345974833
purpose: []
